[package]
name = "max_pairwise_prod"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "max_pairwise_benchmark"
harness = false

